# Generated by Django 4.2.7 on 2024-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gender_user_who_looking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='who_looking',
            field=models.CharField(choices=[('Девушек', 'Девушек'), ('Парней', 'Парней'), ('Без разницы', 'Без разницы')], default='Парней', max_length=11, verbose_name='Кого ищет?'),
        ),
    ]
