# Generated by Django 4.2.7 on 2024-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_age_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Токен авторизации'),
        ),
    ]
