# Generated by Django 4.2.7 on 2024-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='users/video/', verbose_name='Видео'),
        ),
    ]
