# Generated by Django 4.2.7 on 2024-07-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_who_looking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст с информацией о нарушении')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('accused_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_accusations', to=settings.AUTH_USER_MODEL, verbose_name='Обвиняемый пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Обратившийся пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-date_created'],
            },
        ),
    ]
